_wandb:
    value:
        cli_version: 0.21.4
        e:
            4bw85xudchiht5f9tkpmtobrh05xi8bk:
                cpu_count: 4
                cpu_count_logical: 8
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "982238978048"
                        used: "255532613632"
                email: silvapi1994@gmail.com
                executable: /home/silva/SILVA.AI/Projects/MyLLM/.venv/bin/python
                git:
                    commit: 33dd9335cf87566e7c81c46b1e3d5ce4235a2817
                    remote: git@github.com:silvaxxx1/MyLLM.git
                gpu: NVIDIA GeForce GTX 1650
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 1024
                      memoryTotal: "4294967296"
                      name: NVIDIA GeForce GTX 1650
                      uuid: GPU-605b6ad0-c95a-c7a0-f428-928e6885f80f
                host: SilvaLAB
                memory:
                    total: "14521057280"
                os: Linux-6.14.0-32-generic-x86_64-with-glibc2.39
                program: -m myllm.Train.sft_test
                python: CPython 3.12.3
                root: ./sft_output
                startedAt: "2025-09-29T11:13:35.983129Z"
                writerId: 4bw85xudchiht5f9tkpmtobrh05xi8bk
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 2
                - 3
                - 49
            "2":
                - 1
                - 2
                - 3
                - 49
            "3":
                - 15
                - 16
                - 61
            "4": 3.12.3
            "5": 0.21.4
            "10":
                - 21
            "12": 0.21.4
            "13": linux-x86_64
batch_size:
    value: 2
beta1:
    value: null
beta2:
    value: null
data_path:
    value: null
dataloader_num_workers:
    value: 4
dataset_name:
    value: null
dataset_text_field:
    value: text
deepspeed_config_path:
    value: null
device:
    value: auto
distributed_backend:
    value: nccl
eval_steps:
    value: 5
gradient_accumulation_steps:
    value: 1
greater_is_better:
    value: true
instruction_template:
    value: |-
        ### Instruction:
        {instruction}

        ### Response:
        {response}
learning_rate:
    value: 5e-05
load_best_model_at_end:
    value: false
local_rank:
    value: -1
log_model:
    value: true
log_predictions:
    value: false
logging_steps:
    value: 50
max_grad_norm:
    value: 1
max_seq_length:
    value: null
metric_for_best_model:
    value: null
mixed_precision:
    value: true
model_config_name:
    value: gpt2-small
model_config_path:
    value: null
num_epochs:
    value: 2
optimizer_type:
    value: ADAMW
output_dir:
    value: ./sft_output
packing:
    value: false
peft_config:
    value: null
preprocessing_num_workers:
    value: 4
report_to:
    value:
        - wandb
response_template:
    value: '### Response:'
resume_from_checkpoint:
    value: null
save_steps:
    value: 10
save_total_limit:
    value: 3
scheduler_type:
    value: LINEAR
seed:
    value: 42
tensorboard_log_dir:
    value: null
tokenizer_name:
    value: gpt2
use_deepspeed:
    value: false
use_peft:
    value: false
warmup_steps:
    value: 0
weight_decay:
    value: null
