_wandb:
    value:
        cli_version: 0.21.4
        e:
            v9whvfazsqva0ixwjwx8yd9hutxmngst:
                cpu_count: 4
                cpu_count_logical: 8
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "982238978048"
                        used: "279100465152"
                email: silvapi1994@gmail.com
                executable: /home/silva/SILVA.AI/Projects/MyLLM/.venv/bin/python
                git:
                    commit: 1a0ff40931daba38b9ab4e492d01f262a51d3c3f
                    remote: git@github.com:silvaxxx1/MyLLM.git
                gpu: NVIDIA GeForce GTX 1650
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 1024
                      memoryTotal: "4294967296"
                      name: NVIDIA GeForce GTX 1650
                      uuid: GPU-605b6ad0-c95a-c7a0-f428-928e6885f80f
                host: SilvaLAB
                memory:
                    total: "14521057280"
                os: Linux-6.14.0-32-generic-x86_64-with-glibc2.39
                program: -m myllm.Train.examples.run_all_tests
                python: CPython 3.12.3
                root: /home/silva/SILVA.AI/Projects/MyLLM
                startedAt: "2025-09-29T18:01:16.533983Z"
                writerId: v9whvfazsqva0ixwjwx8yd9hutxmngst
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 2
                - 3
                - 49
            "2":
                - 1
                - 2
                - 3
                - 49
            "3":
                - 2
                - 13
                - 16
                - 61
            "4": 3.12.3
            "5": 0.21.4
            "12": 0.21.4
            "13": linux-x86_64
batch_size:
    value: 1
gradient_accumulation_steps:
    value: 1
learning_rate:
    value: 0.0003
max_grad_norm:
    value: 0
model_config_name:
    value: gpt2-small
num_epochs:
    value: 1
tokenizer_name:
    value: gpt2
warmup_steps:
    value: 0
